In [1]:
!pip install numpy

In [1]:
import numpy as np
np.__version__

'1.23.5'

In [3]:
a = [1,2,3,4,5,6,7,8,9,10]
np_array = np.array(a)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
print(np_array + 10)
print(np_array - 10)
print(np_array * 10)
print(np_array / 10)

[11 12 13 14 15 16 17 18 19 20]
[-9 -8 -7 -6 -5 -4 -3 -2 -1  0]
[ 10  20  30  40  50  60  70  80  90 100]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [5]:
a = [1,2,3,4,5,6,7,8,9,10]
np_array = np.array(a)
np_array.shape

(10,)

In [8]:
a = [[[1,1,1],[2,2,2],[3,3,3]],
     [[4,4,4],[5,5,5],[6,6,6]],
     [[7,7,7],[8,8,8],[9,9,9]]]
np_array = np.array(a)
print(np_array.shape)
print(np_array.dtype)

(3, 3, 3)
int32


In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# Reshape
# 6 -> 1 * 6
# 6 -> 6 * 1
# 6 -> 2 * 3
# 6 -> 3 * 2

i = [[1,2,3],
     [4,5,6]]

np_array = np.array(a)
print(np_array.reshape(1,6))
print(np_array.reshape(6,1))
print(np_array.reshape(2,3))
print(np_array.reshape(3,2))

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [15]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a + b
print(c)

[ 7  9 11 13 15]


In [16]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
a = np.array([1+5j,2+3j,3+2j,4+3j,5+2j])
b = np.array([6,7,8,9,10])
a*b

array([ 6.+30.j, 14.+21.j, 24.+16.j, 36.+27.j, 50.+20.j])

In [20]:
# Random Numbers
print(np.random.rand(5,5))

[[0.08971602 0.49318927 0.82028032 0.94485322 0.21068251]
 [0.11107343 0.96076185 0.85383973 0.17266259 0.80073345]
 [0.98319083 0.97377959 0.97414215 0.74457333 0.45113256]
 [0.6686823  0.68901394 0.49258703 0.27211715 0.1255245 ]
 [0.35391089 0.33775684 0.71828717 0.02573323 0.42657459]]


In [21]:
print(np.random.randint(0,10,size=[5,5]))

[[2 8 3 8 3]
 [3 3 6 7 7]
 [9 1 3 7 7]
 [2 9 6 8 7]
 [2 3 7 0 3]]


In [22]:
print(np.random.randint(0,10,size=[100,100]))

[[2 0 7 ... 0 1 7]
 [6 2 0 ... 1 7 9]
 [4 8 6 ... 2 4 8]
 ...
 [7 0 8 ... 5 4 7]
 [5 1 8 ... 0 7 2]
 [8 5 3 ... 8 8 0]]


In [23]:
print(np.random.random(size=[5,5]))

[[0.63771998 0.18649421 0.66591053 0.03782443 0.09332726]
 [0.84518068 0.47694827 0.40288545 0.27041825 0.77704726]
 [0.44683579 0.95566432 0.93696694 0.37869333 0.33773892]
 [0.121677   0.58405919 0.39234507 0.79123807 0.22682085]
 [0.74156599 0.29797219 0.41340013 0.21198292 0.81459378]]


In [25]:
print(np.random.choice(['a','e','i','o','u'], size = 10))

['u' 'u' 'e' 'i' 'o' 'e' 'e' 'i' 'i' 'o']


In [26]:
print(np.random.choice(['a','e','i','o','u'], size = 10, p = [0.3,0.1,0.1,0.4,0.1]))

['a' 'a' 'a' 'o' 'u' 'i' 'e' 'o' 'o' 'u']


In [20]:
na = np.array([1,2,3,4,5,6,7,8,9,10])
print("The minimum value = " , np.min(na))
print("The maximum value = " , np.max(na))
print("The mean value = " , np.mean(na))
print("The median value = " , np.median(na))
print("The standard deviation value = " , np.std(na))

The minimum value =  1
The maximum value =  10
The mean value =  5.5
The median value =  5.5
The standard deviation value =  2.8722813232690143


In [17]:
a = [34,56,78,23,45,67,89,1,89,45,67,34,78,90,340]
a.sort()
a

[1, 23, 34, 34, 45, 45, 56, 67, 67, 78, 78, 89, 89, 90, 340]

In [18]:
np.median(a)
np.std(a)

75.13673461688956

In [21]:
# Matrix Operation
import scipy.linalg as slin
import numpy as np
a = np.array([[3, -5 , 8],
              [-1 ,2 ,3],
              [-5,-6,2]])

slin.det(a)

259.0

In [25]:
import numpy as np
a = np.array([[3, -5 , 8],
              [-1 , 2 ,3],
              [-5 , -6 , 2]])

np.trace(a)
np.transpose(a)

array([[ 3, -1, -5],
       [-5,  2, -6],
       [ 8,  3,  2]])

In [24]:
import scipy.linalg as slin
import numpy as np
a = np.array([[3, -5 , 8],
              [-1 ,2 ,3],
              [-5,-6,2]])

slin.inv(a)

array([[ 0.08494208, -0.14671815, -0.11969112],
       [-0.05019305,  0.17760618, -0.06563707],
       [ 0.06177606,  0.16602317,  0.003861  ]])

In [26]:
import numpy as np
a = np.matrix([[3 , -5 , 8],
               [-1 , 2 , 3],
               [-5 , -6 , 2]])
b = np.matrix([[3],
               [4],
               [-1]])
a * b

matrix([[-19],
        [  2],
        [-41]])

In [27]:
# Eigen value problem

import numpy as np
mat = np.array([[1,2,3] , [4,5,6] , [4,5,6]])

np.linalg.eig(mat)

(array([ 1.27082039e+01, -7.08203932e-01, -2.65381787e-17]),
 array([[ 0.28907816,  0.90041255,  0.40824829],
        [ 0.67691721, -0.30761765, -0.81649658],
        [ 0.67691721, -0.30761765,  0.40824829]]))

In [28]:
# Finding the value of x,y,z in any 3 equations
# x1 + y1 + z1 = a
# x2 + y2 + z2 = b
# x3 + y3 + z3 = c

import numpy as np

a= np.array([[1,1,1],[1.5,4,3],[1,2,3]])
b = np.array([2,5,6])
np.linalg.solve(a,b)

array([ 0.28571429, -0.57142857,  2.28571429])